from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path

from .agent import RepoIntelligenceAgent
from .models import ComplianceReport


def _generate_compliance_report(report: ComplianceReport, output_dir: Path) -> None:
    """Generate COMPLIANCE_REPORT.md from scan results."""
    lines = [
        "# Compliance Scan Report",
        "",
        f"**Scan Date:** {report.scan_timestamp}",
        f"**Repository:** {report.repo_name}",
        "",
        "## Executive Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Files Scanned | {report.total_files_scanned} |",
        f"| Files with Findings | {report.files_with_findings} |",
        f"| Critical Findings | {len(report.critical_findings)} |",
        f"| High Findings | {len(report.high_findings)} |",
        f"| Medium Findings | {len(report.medium_findings)} |",
        f"| Low Findings | {len(report.low_findings)} |",
        "",
        "## Compliance Status",
        "",
        f"- **HIPAA Compliant:** {'YES' if report.hipaa_compliant else 'NO - PHI detected in code'}",
        f"- **PCI Compliant:** {'YES' if report.pci_compliant else 'NO - Payment card data detected'}",
        f"- **AI Safe:** {'YES' if report.ai_safe else 'NO - External AI blocked'}",
        "",
    ]

    if not report.ai_safe:
        lines.extend([
            "### AI Blocked",
            "",
            f"> {report.ai_blocked_reason}",
            "",
        ])

    # Critical findings
    if report.critical_findings:
        lines.extend([
            "## Critical Findings (Must Fix)",
            "",
            "| File | Line | Issue | Category | Recommendation |",
            "|------|------|-------|----------|----------------|",
        ])
        for f in report.critical_findings:
            lines.append(
                f"| `{f.file_path}` | {f.line_number or 'N/A'} | {f.description} | {f.category.upper()} | {f.recommendation} |"
            )
        lines.append("")

    # High findings
    if report.high_findings:
        lines.extend([
            "## High Findings (Should Fix)",
            "",
            "| File | Line | Issue | Category |",
            "|------|------|-------|----------|",
        ])
        for f in report.high_findings[:50]:  # Limit output
            lines.append(f"| `{f.file_path}` | {f.line_number or 'N/A'} | {f.description} | {f.category.upper()} |")
        if len(report.high_findings) > 50:
            lines.append(f"| ... | ... | *{len(report.high_findings) - 50} more findings* | ... |")
        lines.append("")

    # Medium findings (summary only)
    if report.medium_findings:
        lines.extend([
            "## Medium Findings (Review Recommended)",
            "",
            f"*{len(report.medium_findings)} medium-severity findings detected.*",
            "",
            "Categories found:",
        ])
        categories = {}
        for f in report.medium_findings:
            categories[f.category] = categories.get(f.category, 0) + 1
        for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
            lines.append(f"- {cat.upper()}: {count}")
        lines.append("")

    # Recommendations
    lines.extend([
        "## Remediation Steps",
        "",
        "1. **Critical findings:** Fix immediately before any deployment",
        "2. **PHI/PII data:** Remove from code, use secure data stores",
        "3. **Credentials:** Move to environment variables or secrets manager",
        "4. **Test data:** Use synthetic data generators instead of realistic values",
        "",
        "## Next Steps",
        "",
        "- [ ] Review all critical findings",
        "- [ ] Remove hardcoded sensitive data",
        "- [ ] Re-run scan to verify fixes: `repo-intel --compliance-scan`",
        "- [ ] Add pre-commit hooks to prevent future violations",
        "",
        "---",
        "*Generated by RunBook-AI Compliance Scanner*",
    ])

    report_path = output_dir / "COMPLIANCE_REPORT.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Compliance report written to: {report_path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="repo-intel",
        description="Generic repository intelligence agent with adaptive documentation generation.",
    )
    parser.add_argument(
        "repo",
        nargs="?",
        default=".",
        help="Path to the repository to analyze. Defaults to the current directory.",
    )
    parser.add_argument(
        "--output-docs",
        type=Path,
        help="Write generated documentation artifacts to this directory.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the repository profile as JSON.",
    )
    parser.add_argument(
        "--use-ai",
        action="store_true",
        help="Refine generated documentation with the OpenAI Responses API.",
    )
    parser.add_argument(
        "--provider",
        choices=["openai", "bedrock"],
        default="openai",
        help="AI provider to use with --use-ai. Defaults to openai.",
    )
    parser.add_argument(
        "--model",
        default="gpt-4.1-mini",
        help="Model ID to use with --use-ai. Defaults to gpt-4.1-mini for OpenAI.",
    )
    parser.add_argument(
        "--aws-region",
        help="AWS region for Bedrock (e.g., us-east-1, us-west-2).",
    )
    parser.add_argument(
        "--aws-profile",
        help="AWS CLI profile name for Bedrock authentication.",
    )
    parser.add_argument(
        "--aws-role-arn",
        help="IAM role ARN to assume for Bedrock access.",
    )
    # Word document options
    parser.add_argument(
        "--word",
        action="store_true",
        help="Generate ISMS-compliant Word documents (.docx) in addition to Markdown.",
    )
    parser.add_argument(
        "--organization",
        default="Organization Name",
        help="Organization name for Word document headers.",
    )
    parser.add_argument(
        "--department",
        default="Engineering",
        help="Department name for Word document metadata.",
    )
    parser.add_argument(
        "--classification",
        default="Internal",
        choices=["Public", "Internal", "Confidential", "Restricted"],
        help="Document classification level.",
    )
    # Healthcare compliance options
    parser.add_argument(
        "--healthcare",
        action="store_true",
        help="Enable healthcare compliance mode (HIPAA). Scans for PHI/PII and blocks AI if found.",
    )
    parser.add_argument(
        "--compliance-scan",
        action="store_true",
        help="Run compliance scan for PHI/PII/credentials without blocking AI.",
    )
    parser.add_argument(
        "--compliance-level",
        choices=["quick", "standard", "thorough"],
        default="standard",
        help="Compliance scan depth. quick=critical only, standard=critical+high, thorough=all.",
    )
    parser.add_argument(
        "--force-ai",
        action="store_true",
        help="Force AI refinement even if compliance issues found (NOT RECOMMENDED for healthcare).",
    )
    parser.add_argument(
        "--all-docs",
        action="store_true",
        help="Generate all 9 document types regardless of what's detected in the repo.",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    # Ensure output directory exists early (before any processing)
    if args.output_docs:
        output_path = Path(args.output_docs).resolve()
        output_path.mkdir(parents=True, exist_ok=True)
        args.output_docs = output_path  # Use resolved path

    # Healthcare mode enables compliance scanning and blocks AI by default
    compliance_enabled = args.healthcare or args.compliance_scan
    compliance_level = args.compliance_level

    agent = RepoIntelligenceAgent(
        compliance_scan=compliance_enabled,
        compliance_level=compliance_level,
        generate_all_docs=args.all_docs,
    )
    agent.doc_refiner.provider = args.provider
    agent.doc_refiner.model = args.model
    agent.doc_refiner.aws_region = args.aws_region
    agent.doc_refiner.aws_profile = args.aws_profile
    agent.doc_refiner.aws_role_arn = args.aws_role_arn

    # Determine if AI should be used
    use_ai = args.use_ai
    ai_blocked = False
    block_reason = ""

    if args.output_docs:
        result = agent.write_docs(args.repo, args.output_docs, use_ai=False)  # First pass without AI
    else:
        result = agent.run(args.repo, use_ai=False)

    # Check compliance results before AI
    compliance_report = agent.analyzer.compliance_report
    if compliance_report and compliance_report.has_blockers:
        if args.healthcare and not args.force_ai:
            ai_blocked = True
            block_reason = compliance_report.ai_blocked_reason
            use_ai = False
        elif use_ai and not args.force_ai:
            print(f"\n{'='*60}")
            print("WARNING: Compliance issues detected!")
            print(f"{'='*60}")
            print(f"Critical findings: {len(compliance_report.critical_findings)}")
            print(f"High findings: {len(compliance_report.high_findings)}")
            print("\nAI refinement will proceed, but review findings carefully.")
            print("Use --healthcare to block AI when PHI/PII detected.")
            print(f"{'='*60}\n")

    # Run AI refinement if allowed
    if use_ai and not ai_blocked:
        result = agent.write_docs(args.repo, args.output_docs, use_ai=True) if args.output_docs else agent.run(args.repo, use_ai=True)

    # Generate compliance report if scan was enabled
    if compliance_report and args.output_docs:
        _generate_compliance_report(compliance_report, args.output_docs)

    # Print compliance summary
    if compliance_report:
        print(f"\n{'='*60}")
        print("COMPLIANCE SCAN RESULTS")
        print(f"{'='*60}")
        print(f"Files scanned: {compliance_report.total_files_scanned}")
        print(f"Files with findings: {compliance_report.files_with_findings}")
        print(f"Critical: {len(compliance_report.critical_findings)}")
        print(f"High: {len(compliance_report.high_findings)}")
        print(f"Medium: {len(compliance_report.medium_findings)}")
        print(f"Low: {len(compliance_report.low_findings)}")
        print(f"\nHIPAA Compliant: {'YES' if compliance_report.hipaa_compliant else 'NO'}")
        print(f"PCI Compliant: {'YES' if compliance_report.pci_compliant else 'NO'}")
        print(f"AI Safe: {'YES' if compliance_report.ai_safe else 'NO'}")
        if ai_blocked:
            print(f"\nAI BLOCKED: {block_reason}")
        print(f"{'='*60}\n")

    # Generate Word documents if requested
    if args.word and args.output_docs:
        from .word_generator import ISMSDocumentGenerator

        word_gen = ISMSDocumentGenerator(
            organization=args.organization,
            department=args.department,
            classification=args.classification,
        )
        word_dir = args.output_docs / "word"
        word_files = word_gen.generate_all(result.artifacts, result.profile, word_dir)
        print(f"Word documents generated: {len(word_files)}")
        for wf in word_files:
            print(f"  - {wf.name}")

    if args.json:
        print(json.dumps(asdict(result.profile), default=str, indent=2))
        return

    print(f"Repository: {result.profile.name}")
    print(f"Files scanned: {result.profile.total_files}")
    print(f"Languages: {', '.join(result.profile.languages.keys()) or 'None detected'}")
    print(f"Documentation needs: {', '.join(result.profile.doc_needs)}")
    print(f"AI refinement: {'enabled' if args.use_ai else 'disabled'}")
    if args.use_ai:
        print(f"AI provider: {args.provider}")
        print(f"AI model: {agent.doc_refiner.model}")
    if result.warnings:
        print("Warnings:")
        for warning in result.warnings:
            print(f"- {warning}")
    print("Generated artifacts:")
    for artifact in result.artifacts:
        suffix = " (AI refined)" if artifact.generated_with_ai else ""
        print(f"- {artifact.filename}{suffix}")
